config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    
    resources :customers, only: [:index, :show, :edit, :update]
    
    resources :orders, only: [:show]
  end
  
  scope module: :public do
    root to: 'homes#top'
    
    get 'about' => 'homes#about'
    
    resources :items, only: [:index, :show]
    
    resources :customers, only: [:show, :update, :edit]
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
        
    resources :cart_items do
      delete :destroy_all, on: :collection
    end
    
    resources :orders do
      post :check, on: :collection
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_items

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  # 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  
  def new
    @item = Item.new
  end 
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の保存に成功しました。"
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end 
  
  def show
    @item = Item.find(params[:id])
  end 
  
  def edit
    @item = Item.find(params[:id])
  end 
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "編集に成功しました。"
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end
  
  def destroy
    item = Item.find(params[:id])
    item.destroy
    flash[:notice] = "商品を削除しました。"
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>商品編集</h2>
    </div>
  </div>
   <div class="row">  
    <div class="col-sm-10 px-sm-0 mx-auto">
      <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
      <table>
      <tr>
        <div class="form-group">
          <th><%= f.label :商品画像 %></th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :商品名 %></th>
          <td><%= f.text_field :name, placeholder:"商品名" %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :商品説明 %></th>
          <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :税抜価格 %></th>
          <td><%= f.text_field :price, placeholder:"1000" %>円</td>
        </div>
      </tr>
      <tr>
        <div class="form-action">
          <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
        </div>
      </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>商品一覧</h2>
    </div>
    <div class="col-sm-2 px-sm-0 text-right mb-2">
      <%= link_to new_admin_item_path, class:"btn btn--circle btn--circle-c btn--shadow" do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </div>
    <div class="row">
      <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <table class="table text-center admin-items mb-5">
          <thead>
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
            </tr>
          </thead>
          <% @items.each do |item| %>
          <tbody>
            <tr>
              <td class="align-middle"><%= item.id %></td>
              <td class="align-middle"><%= link_to admin_item_path(item.id) do %>
                <u><%= item.name %></u>
              </td>
              <% end %>
              <td class="align-middle"><%= item.price %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      <%#= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>商品新規登録</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品画像 %></th>
            <th><%= f.file_field :image %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品説明 %></th>
              <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
          </div>
        </tr>
        <tr>
        <div class="form-group">
          <th><%= f.label :税抜価格 %></th>
          <td><%= f.text_field :price, placeholder:"1000" %>円</td>
        </div>
        </tr>
        <tr>
        <div class="form-action">
          <th><%= f.submit "新規登録", class:"btn btn-success" %></th>
        </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<h3>商品詳細</h3>
  <%= image_tag @item.image, size: "300x200" %>
<h4>商品名</h4>
  <%= @item.name %>
<h4>商品説明</h4>
  <%= @item.introduction %>
<h4>税込価格（税抜価格）</h4>
  <%= @item.price %>
<%= link_to '編集する', edit_admin_item_path(@item.id), class: "btn btn-success" %>