config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    
    resources :customers, only: [:index, :show, :edit, :update]
    
    resources :orders, only: [:show]
  end
  
  scope module: :public do
    root to: 'homes#top'
    
    get 'about' => 'homes#about'
    
    resources :items, only: [:index, :show]
    
    resources :customers, only: [:show, :update, :edit]
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
        
    resources :cart_items do
      delete :destroy_all, on: :collection
    end
    
    resources :orders do
      post :check, on: :collection
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <% if admin_signed_in? %>
        <%= link_to 'ながのケーキ', root_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to 'ながのケーキ', root_path, class: "navbar-brand" %>
      <% end %>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Taggle navigaion">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
        <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to current_customer, class: 'nav-link' do %>
                マイページ
              <% end %>
            <li class="nav-item">
              <%= link_to items_path do %>
                商品一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to cart_items_path do %>
                カート
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_customer_session_path, method: :delete do %>
                ログアウト
              <% end %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_items_path do %>
                商品一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_customers_path do %>
                会員一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_customers_path do %>
                注文履歴一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete do %>
                ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to about_path do %>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to items_path do %>
                商品一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_registration_path do %>
                新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_session_path do %>
                ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mb-4">
      <%= render 'layouts/header' %>
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>